In [2]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-1.5.2-py2.py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.3.5)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.5)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2025.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.2.6-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.13.5)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.15.0-cp310-abi3-macosx_11_0_arm64.whl.metadata (18 kB)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-16.1.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.8 kB)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2025.11.12)
Requirement already satisfied: rich in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (14.2.0)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Downloading yfinance-1.5.2-py2.py3-none-any.whl (144 kB)
Downloading curl_cffi-0.15.0-cp310-abi3-macosx_11_0_arm64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 3.2 MB/s  0:00:00m 3.1 MB/s eta 0:00:01
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.2.6-py3-none-any.whl (173 kB)
Downloading websockets-16.1.1-cp313-cp313-macosx_11_0_arm64.whl (177 kB)
Installing collected packages: peewee, multitasking, websockets, curl_cffi, yfinance
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [yfinance]━━ 4/5 [yfinance]s]
Successfully installed curl_cffi-0.15.0 multitasking-0.0.13 peewee-4.2.6 websockets-16.1.1 yfinance-1.5.2

In [1]:
import yfinance as yf
import pandas as pd
compass = yf.Ticker("CPG.L")
pd.set_option('display.float_format', lambda x: '%.2f' % x)

income_statement = compass.financials
income_statement_3yr = income_statement.iloc[:, :3]
print("--- Income Statement ---")
display(income_statement_3yr)

balance_sheet = compass.balance_sheet
balance_sheet_3yr = balance_sheet.iloc[:, :3]
print("--- Balance Sheet ---")
display(balance_sheet_3yr)

cash_flow = compass.cashflow
cash_flow_3yr = cash_flow.iloc[:, :3]
print("--- Cash Flow Statement ---")
display(cash_flow_3yr)

--- Income Statement ---

,2025-09-30,2024-09-30,2023-09-30
Tax Effect Of Unusual Items,-117151702.79,-214520428.02,-85362000.00
Tax Rate For Calcs,0.27,0.31,0.25
Normalized EBITDA,4582000000.00,4098000000.00,3657000000.00
Total Unusual Items,-430000000.00,-687000000.00,-347000000.00
Total Unusual Items Excluding Goodwill,-430000000.00,-687000000.00,-347000000.00
Net Income From Continuing Operation Net Minority Interest,1868000000.00,1404000000.00,1607000000.00
Reconciled Depreciation,852000000.00,744000000.00,670000000.00
Reconciled Cost Of Revenue,30677000000.00,28076000000.00,25567000000.00
EBITDA,4152000000.00,3411000000.00,3310000000.00
EBIT,2962000000.00,2361000000.00,2358000000.00
Net Interest Income,-356000000.00,-277000000.00,-175000000.00
Interest Expense,378000000.00,305000000.00,221000000.00
Interest Income,29000000.00,30000000.00,53000000.00
Normalized Income,2180848297.21,1876479571.98,1868638000.00
Net Income From Continuing And Discontinued Operation,1868000000.00,1404000000.00,1607000000.00
Total Expenses,42775000000.00,39054000000.00,35339000000.00
Rent Expense Supplemental,NaN,192000000.00,182000000.00
Total Operating Income As Reported,2964000000.00,2584000000.00,2245000000.00
Diluted Average Shares,1699000000.00,1707000000.00,1745000000.00
Basic Average Shares,1697000000.00,1705000000.00,1743000000.00
Diluted EPS,1.10,0.82,0.92
Basic EPS,1.10,0.82,0.92
Diluted NI Availto Com Stockholders,1868000000.00,1404000000.00,1607000000.00
Net Income Common Stockholders,1868000000.00,1404000000.00,1607000000.00
Otherunder Preferred Stock Dividend,0.00,0.00,0.00
Net Income,1868000000.00,1404000000.00,1607000000.00
Minority Interests,-12000000.00,-10000000.00,-5000000.00
Net Income Including Noncontrolling Interests,1880000000.00,1414000000.00,1612000000.00
Net Income Continuous Operations,1880000000.00,1414000000.00,1612000000.00
Tax Provision,704000000.00,642000000.00,525000000.00
Pretax Income,2584000000.00,2056000000.00,2137000000.00
Special Income Charges,-410000000.00,-620000000.00,-299000000.00
Other Special Charges,31000000.00,203000000.00,-24000000.00
Write Off,8000000.00,3000000.00,77000000.00
Impairment Of Capital Assets,NaN,146000000.00,60000000.00
Restructuring And Mergern Acquisition,371000000.00,414000000.00,186000000.00
Net Non Operating Interest Income Expense,-356000000.00,-277000000.00,-175000000.00
Total Other Finance Cost,7000000.00,2000000.00,7000000.00
Interest Expense Non Operating,378000000.00,305000000.00,221000000.00
Interest Income Non Operating,29000000.00,30000000.00,53000000.00
Operating Income,3295000000.00,2948000000.00,2568000000.00
Operating Expense,12098000000.00,10978000000.00,9772000000.00
Other Operating Expenses,7364000000.00,6924000000.00,6001000000.00
Depreciation And Amortization In Income Statement,1190000000.00,1050000000.00,952000000.00
Amortization,521000000.00,456000000.00,416000000.00
Depreciation Income Statement,669000000.00,594000000.00,536000000.00
Selling General And Administration,NaN,11000000.00,10000000.00
General And Administrative Expense,NaN,11000000.00,10000000.00
Rent And Landing Fees,NaN,192000000.00,182000000.00
Gross Profit,15393000000.00,13926000000.00,12340000000.00
Cost Of Revenue,30677000000.00,28076000000.00,25567000000.00
Total Revenue,46070000000.00,42002000000.00,37907000000.00
Operating Revenue,46070000000.00,42002000000.00,37907000000.00

--- Balance Sheet ---

,2025-09-30,2024-09-30,2023-09-30
Treasury Shares Number,88102999.00,88290717.00,70744082.00
Ordinary Shares Number,1697300978.00,1697113260.00,1714659895.00
Share Issued,1785403977.00,1785403977.00,1785403977.00
Net Debt,4851000000.00,3973000000.00,3085000000.00
Total Debt,6992000000.00,5911000000.00,5267000000.00
...,...,...,...
Gross Accounts Receivable,4701000000.00,4263000000.00,3847000000.00
Cash Cash Equivalents And Short Term Investments,575000000.00,623000000.00,1029000000.00
Cash And Cash Equivalents,575000000.00,623000000.00,1029000000.00
Cash Equivalents,99000000.00,186000000.00,647000000.00
Cash Financial,476000000.00,437000000.00,382000000.00

--- Cash Flow Statement ---

,2025-09-30,2024-09-30,2023-09-30
Free Cash Flow,2474000000.00,2234000000.00,1828000000.00
Repurchase Of Capital Stock,-115000000.00,-577000000.00,-1148000000.00
Repayment Of Debt,-882000000.00,-1592000000.00,-543000000.00
Issuance Of Debt,1412000000.00,1381000000.00,1000000.00
Issuance Of Capital Stock,NaN,0.00,-19000000.00
Capital Expenditure,-892000000.00,-901000000.00,-708000000.00
End Cash Position,512000000.00,593000000.00,830000000.00
Other Cash Adjustment Outside Changein Cash,NaN,-40000000.00,NaN
Beginning Cash Position,593000000.00,830000000.00,1934000000.00
Effect Of Exchange Rate Changes,22000000.00,59000000.00,169000000.00
Changes In Cash,-103000000.00,-296000000.00,-1273000000.00
Financing Cash Flow,-1045000000.00,-1942000000.00,-2580000000.00
Net Other Financing Charges,-140000000.00,46000000.00,147000000.00
Cash Dividends Paid,-1047000000.00,-963000000.00,-796000000.00
Common Stock Dividend Paid,-1047000000.00,-963000000.00,-796000000.00
Net Common Stock Issuance,-115000000.00,-577000000.00,-1167000000.00
Common Stock Payments,-115000000.00,-577000000.00,-1148000000.00
Common Stock Issuance,NaN,0.00,-19000000.00
Net Issuance Payments Of Debt,530000000.00,-211000000.00,-542000000.00
Net Long Term Debt Issuance,530000000.00,-211000000.00,-542000000.00
Long Term Debt Payments,-882000000.00,-1592000000.00,-543000000.00
Long Term Debt Issuance,1412000000.00,1381000000.00,1000000.00
Investing Cash Flow,-2424000000.00,-1489000000.00,-1229000000.00
Net Other Investing Changes,-490000000.00,-508000000.00,-380000000.00
Interest Received Cfi,37000000.00,39000000.00,61000000.00
Dividends Received Cfi,43000000.00,65000000.00,60000000.00
Net Investment Purchase And Sale,-98000000.00,328000000.00,0.00
Sale Of Investment,NaN,330000000.00,4000000.00
Purchase Of Investment,-98000000.00,-2000000.00,-4000000.00
Net Business Purchase And Sale,-1091000000.00,-568000000.00,-340000000.00
Sale Of Business,166000000.00,225000000.00,58000000.00
Purchase Of Business,-1257000000.00,-793000000.00,-398000000.00
Net Intangibles Purchase And Sale,-347000000.00,-329000000.00,-263000000.00
Purchase Of Intangibles,-347000000.00,-329000000.00,-263000000.00
Net PPE Purchase And Sale,-478000000.00,-491000000.00,-367000000.00
Sale Of PPE,67000000.00,81000000.00,78000000.00
Purchase Of PPE,-545000000.00,-572000000.00,-445000000.00
Operating Cash Flow,3366000000.00,3135000000.00,2536000000.00
Taxes Refund Paid,-653000000.00,-693000000.00,-539000000.00
Interest Paid Cfo,-327000000.00,-267000000.00,-208000000.00
Change In Working Capital,-40000000.00,186000000.00,-120000000.00
Change In Payable,468000000.00,892000000.00,679000000.00
Change In Inventory,-64000000.00,-36000000.00,-119000000.00
Change In Receivables,-444000000.00,-670000000.00,-680000000.00
Other Non Cash Items,753000000.00,797000000.00,624000000.00
Stock Based Compensation,82000000.00,68000000.00,54000000.00
Provisionand Write Offof Assets,-1000000.00,7000000.00,-50000000.00
Depreciation And Amortization,852000000.00,744000000.00,670000000.00
Amortization Cash Flow,183000000.00,150000000.00,134000000.00
Depreciation,669000000.00,594000000.00,536000000.00
Pension And Employee Benefit Expense,22000000.00,15000000.00,-13000000.00
Gain Loss On Sale Of PPE,0.00,-5000000.00,-4000000.00
Net Income From Continuing Operations,2927000000.00,2540000000.00,2245000000.00

In [3]:
income_statement_3yr.to_csv("compass_income_statement_3yr.csv")
balance_sheet_3yr.to_csv("compass_balance_sheet_3yr.csv")
cash_flow_3yr.to_csv("compass_cash_flow_3yr.csv")